pipeline:
  prepare:
    image: plugins/git
    commands:
      - git clone -b yaml https://github.com/mesalock-linux/packages.git packages
      - git clone https://github.com/mesalock-linux/mkpkg.git mkpkg
  build-mkpkg:
    image: mesalocklinux/build-mesalock-linux
    pull: true
    commands:
      - cd mkpkg && cargo build --release
  build-packages:
    image: mesalocklinux/build-mesalock-linux
    pull: true
    commands:
      - ./build-all.sh
  build-iso:
    image: mesalocklinux/build-mesalock-linux
    pull: true
    commands:
      - ./mesalockiso
  build-rootfs:
    image: mesalocklinux/build-mesalock-linux
    pull: true
    commands:
      - ./mesalockrootfs
  publish-docker-image-develop:
    image: plugins/docker
    repo: mesalocklinux/mesalock-linux
    secrets: [ docker_username, docker_password ]
    tags: [ develop ]
    when:
      branch: develop
      event: push
  publish-docker-image-latest:
    image: plugins/docker
    repo: mesalocklinux/mesalock-linux
    secrets: [ docker_username, docker_password ]
    tags: [ latest ]
    when:
      branch: master
      event: push
  publish-docker-image-tag:
    image: plugins/docker
    repo: mesalocklinux/mesalock-linux
    secrets: [ docker_username, docker_password ]
    default_tags: true
    when:
      event: tag
  notify:
    image: drillster/drone-email
    secrets: [ plugin_host, plugin_username, plugin_password, plugin_from ]
    when:
      status: [ success, changed, failure ]
