#!/bin/bash

set -e

workdir=$(pwd)
rootfs=$workdir/rootfs
dockerdir=$workdir/docker
isodir=$workdir/iso
buildroot=$workdir/build

rm -rf $isodir && mkdir -p $isodir

packages=(linux syslinux)

for p in ${packages[@]}; do
  tar xkfJ $buildroot/out/$p.tar.xz -C $isodir &
done
wait

packages=(filesystem \
          minit \
          mgetty \
          glibc \
          gcc-libs \
          ion-shell \
          uutils-coreutils \
	      giproute2 \
	      busybox \
	      mesalock-demo \
	     )
          # ripgrep \
          # fd-find \
          # tzdata \
          # xi-core \
          # xi-tui \
          # uutils-findutils \
          # tokei \
          # brotli \
          # micro)

rm -rf $rootfs
mkdir -p $rootfs

echo "[+] mesalockiso: installing rootfs"
for p in ${packages[@]}; do
  tar xfkJ build/out/$p.tar.xz -C $rootfs
done

echo "[+] mesalockiso: packaging initramfs"
mkdir -p $isodir/boot
cd $rootfs
find . | sort | fakeroot cpio --quiet -o -H newc | pigz -9 > $isodir/boot/initramfs

echo "[+] mesalockiso: generating iso"
cd $workdir && xorrisofs -o mesalock-linux.iso -l -J -R \
	-b boot/syslinux/isolinux.bin \
	-c boot/syslinux/boot.cat \
	-no-emul-boot -boot-load-size 4 -boot-info-table \
	-quiet -follow-links iso \
	> /dev/null 2>&1
isohybrid mesalock-linux.iso > /dev/null
