#!/bin/bash

set -e

workdir=$(pwd)
builddir=$(pwd)/build
rootfsdir=$builddir/rootfs

echo "[+] mesalockrootfs: installing packages"
packages=(filesystem \
          glibc \
          ion-shell \
          uutils-coreutils \
          ripgrep \
          fd-find \
          tzdata \
          xi-core \
          xi-tui \
          uutils-findutils \
          tokei \
          brotli \
          micro)

rm -rf $rootfsdir
mkdir -p $rootfsdir

for p in ${packages[@]}; do
  tar xkfJ $builddir/out/$p.tar.xz -C $rootfsdir
done

echo "[+] mesalockrootfs: tar and zip rootfs"
tar cfJ $builddir/rootfs.tar.xz -C $rootfsdir .
