#!/bin/bash

export MAKEFLAGS=-j$(nproc)

workdir=$(pwd)
buildroot=$workdir/build
pkgrepo=$workdir/packages

prepare() { :; }
build() { :; }
package() { :; }

. $pkgrepo/$1/BUILD

srcdir=$buildroot/src/$pkgname
builddir=$buildroot/bld/$pkgname
pkgdir=$buildroot/pkg/$pkgname
outdir=$buildroot/out

rm -rf $srcdir $builddir $pkgdir
mkdir -p $srcdir $builddir $pkgdir $outdir

echo "[+} $1: start"
for f in prepare build package; do
  echo "[+] $1: $f"
  cd $buildroot && $f > /dev/null 2>&1
done

echo "[+] $1: tar and zip"
tar cfJ $outdir/$pkgname.tar.xz -C $pkgdir .
echo "[+] $1: done"
